apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-example-dev-staging
  namespace: cert-manager
spec:
  dnsNames:
    - "*.example.dev"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: dme-cluster-issuer-staging
  secretName: star-example-dev-staging-tls
  # secretTemplate:
  #   annotations:
  #     reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
  #     reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  #     reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: sdfhkf2,KH82bs,DHYJgv8
