{{ if .Values.secretRef.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef.name }}
type: Opaque
stringData:
  key: {{ .Values.secretRef.key }}
  secret: {{ .Values.secretRef.secret }}
{{ end }}