{{- if .Values.azureKeyVault.enabled -}}
{{ range $s := .Values.azureKeyVault.secrets }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $s.vaultObjectName }}
  namespace: {{ $.Values.certManager.namespace }}
spec:
  vault:
    name: {{ $s.vaultName}}
    object:
      name: {{ $s.vaultObjectName }}
      type: secret
    {{- if $s.reflect }}
    output:
      secret:
        name: {{ $s.vaultObjectName }}
        dataKey: {{ $s.envVarName }}
    {{ end }}
{{ end }}
{{- end -}}