# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.dme.io
dmeBaseUrl: https://api.sandbox.dnsmadeeasy.com/V2.0
acmeEmail: hostmaster@this.domain

logging:
  # klog (1..10)
  verbosity: 10

replicaCount: 1

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: zombro/cert-manager-dme-webhook
  tag: latest
  pullPolicy: Always
  # pullSecrets:
  #   - name: as-needed

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}

azureKeyVault:
  # webhook will check env vars before calling apiserver to extract any secrets
  # ensure namespace or workload has label: 'azure-key-vault-env-injection: enabled'
  enabled: true
  secrets:
    apiSecret:
      vaultName: example-vault
      vaultObjectName: dme-apisecret-sandbox
      envVarName: DME_API_SECRET
      reflect: false
    apiKey:
      vaultName: example-vault
      vaultObjectName: dme-apikey-sandbox
      envVarName: DME_API_KEY
      reflect: false

secretRef:
  enabled: false
  # secret must have keys 'key' and 'secret'
  # edit values after provisioning
  name: dme-api-secret-sandbox
  key: not-very-secure
  secret: not-very-secure
